version: '3.8'

services:
  ollama:
    # … trzymasz bez zmian …

  gradio:
    build:
      context: ./gradio
      dockerfile: Dockerfile
    image: gradio:latest
    container_name: gradio
    ports:
      - "7860:7860"
    entrypoint: ["python3", "/app/chatbot.py"]
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ollama_network

networks:
  ollama_network:
    driver: bridge
