version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    image: ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/root/.ollama
    volumes:
      - ./app:/app
      - ./model:/root/.ollama
    entrypoint:
      - /bin/bash
      - -c
      - /home/scripts/entrypoint.sh
    restart: unless-stopped
    networks:
      - ollama_network

  gradio:
    build:
      context: ./gradio
      dockerfile: Dockerfile
    image: gradio:latest
    container_name: gradio
    ports:
      - "7860:7860"
    entrypoint:
      - python3
      - /app/chatbot.py
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ollama_network

networks:
  ollama_network:
    driver: bridge
